[debops.gitlab] Don't rely on changed code to run tasks.
debops/debops pull request #101
Opened 2018-01-02 11:39 UTC by bfabio

Don't check if the code of the projects has changed before running tasks,
because it can result in an inconsistent and hard to debug state when a
previous run managed to update the code but failed somewhere after that.

2018-01-03 07:41 UTC, drybjed reviewed
I agree, that design was a horrible idea, and I wanted to drop it for a long time now. Did you test what happens on a normal, completed install? My worry was that there are some destructive tasks which shouldn't be done repeatedly, but if there aren't any I guess we can go with this...

2018-01-03 11:03 UTC, bfabio commented
> Did you test what happens on a normal, completed install?

I did, it works fine on my deploy.

2018-01-03 11:21 UTC, drybjed approved these changes
So, no issues with database migrations, etc.? Very well then. I will merge it soon, test environment is up and I'm checking all roles again to have a baseline.

2018-01-03 11:53 UTC, bfabio commented
No issues at all, Rails migrations are designed to be idempotent.

2018-01-03 19:20 UTC, drybjed commented
I've checked the idempotency of this PR and unfortunately, there are issues:
```
TASK [debops.gitlab : Setup gitlab-shell] **************************************
changed: [localhost]
```
The `gitlab-shell` setup seems to not be idempotent. Perhaps you could register the task output and add a condition that detects the state of the task to handle idempotency better.

```
TASK [debops.gitlab : Setup gitlab-workhorse] **********************************
changed: [localhost]
```
This task doesn't seem to be idempotent as well, and similarly the output should be checked.

```
TASK [debops.gitlab : Yarn install] ********************************************
changed: [localhost]

TASK [debops.gitlab : Update Ruby gems] ****************************************
changed: [localhost]
```
The Yarn and Ruby gems also aren't idempotent.

```
TASK [debops.gitlab : Migrate GitLab database] *********************************
changed: [localhost]
```
Does database migration have any good indication of an idempotent state?

```
TASK [debops.gitlab : Clean GitLab assets] *************************************
changed: [localhost]

TASK [debops.gitlab : Precompile GitLab assets] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bundle", "exec", "rake", "gitlab:assets:compile", "RAILS_ENV=production", "NODE_ENV=production"], "delta": "0:02:44.854458", "end": "2018-01-03 19:07:41.437545", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-01-03 19:04:56.583087", "stderr": "/var/local/git/gitlab/node_modules/.bin/webpack --config /var/local/git/gitlab/config/webpack.config.js --bail\nFATAL ERROR: Committing semi space failed. Allocation failed - process out of memory\n 1: node::Abort() [node]\n 2: 0x10a03cc [node]\n 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]\n 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]\n 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]\n 6: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [node]\n 7: v8::internal::Heap::CollectAllAvailableGarbage(char const*) [node]\n 8: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]\n 9: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]\n10: 0xc42ed4079a7\nrake aborted!\nCommand failed with status (): [/var/local/git/gitlab/node_modules/.bin/we...]\n/var/local/git/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'\nTasks: TOP => gitlab:assets:compile => webpack:compile\n(See full trace by running task with --trace)", "stderr_lines": ["/var/local/git/gitlab/node_modules/.bin/webpack --config /var/local/git/gitlab/config/webpack.config.js --bail", "FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory", " 1: node::Abort() [node]", " 2: 0x10a03cc [node]", " 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]", " 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]", " 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]", " 6: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [node]", " 7: v8::internal::Heap::CollectAllAvailableGarbage(char const*) [node]", " 8: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]", " 9: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]", "10: 0xc42ed4079a7", "rake aborted!", "Command failed with status (): [/var/local/git/gitlab/node_modules/.bin/we...]", "/var/local/git/gitlab/vendor/bundle/ruby/2.3.0/gems/webpack-rails-0.9.10/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'", "/var/local/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'", "Tasks: TOP => gitlab:assets:compile => webpack:compile", "(See full trace by running task with --trace)"], "stdout": "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/pl_PL\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/ko\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/pt_BR\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/bg\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/ru\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/eo\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/zh_HK\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/uk\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/fr\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/de\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/nl_NL\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/ja\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/es\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/it\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/zh_TW\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/zh_CN\nCreated app.js in /var/local/git/gitlab/app/assets/javascripts/locale/en\n\nAll files created, make sure they are being added to your assets.\nIf they are not, you can add them with this line (configurable):\n\n//= require_tree ./locale\n//= require gettext/all\n\n\n<--- Last few GCs --->\n\n  117204 ms: Mark-sweep 360.7 (2169545.2) -> 360.1 (2171534.2) MB, 831.5 / 0.0 ms [allocation failure] [scavenge might not succeed].\n  118165 ms: Mark-sweep 360.1 (2171535.2) -> 360.1 (2202789.2) MB, 958.8 / 0.0 ms [allocation failure] [GC in old space requested].\n  119110 ms: Mark-sweep 360.1 (2202790.2) -> 360.1 (2234424.2) MB, 945.1 / 0.0 ms [allocation failure] [GC in old space requested].\n  120049 ms: Mark-sweep 360.1 (2234425.2) -> 360.1 (2266021.2) MB, 938.7 / 0.0 ms [last resort gc].\n\n\n<--- JS stacktrace --->\n\n==== JS stack trace =========================================\n\nSecurity context: 0x34d56d9cf781 <JS Object>\n    1: parseExprList [/var/local/git/gitlab/node_modules/acorn-dynamic-import/node_modules/acorn/dist/acorn.js:~2400] [pc=0xc42f0f433e4] (this=0x36fa481e4939 <a Parser with map 0x1c3728fb95e1>,close=0x146a683e059 <a TokenType with map 0x4bd6808ea29>,allowTrailingComma=0x34d56d9043c1 <true>,allowEmpty=0x34d56d904271 <false>,refDestructuringErrors=0x2cf383c1d771 <a DestructuringErrors with map 0x...", "stdout_lines": ["Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/pl_PL", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/ko", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/pt_BR", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/bg", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/ru", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/eo", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/zh_HK", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/uk", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/fr", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/de", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/nl_NL", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/ja", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/es", "Created app.js in /var/local/git/gitlab/app/assets/javascripts/locale/it", "Created app.js in /var/local/git/gitlab/app/assets/javascript [...]

2018-01-03 19:20 UTC, drybjed requested changes
Waiting for fixes per the previous comment.

2022-07-20 04:48 UTC, drybjed commented
The `gitlab` role in DebOps has been rewritten and now supports GitLab Omnibus installation instead of source installation. This PR is now obsolete, so I'm closing it.

2022-07-20 04:48 UTC, closed without merging