[debops.system_users] Add missing dependent variables to manage on the current playbook host
debops/debops pull request #1105
Opened 2019-10-17 14:31 UTC by reixd

2019-10-19 08:20 UTC, drybjed commented on ansible/roles/debops.system_users/defaults/main.yml
> +                                     + system_users__dependent_groups
You probably would also want to flatten this variable as well.

2019-10-19 08:22 UTC, drybjed requested changes
Well... From my point of view the `user` and `group` Ansible modules should be enough for Ansible roles to create the needed UNIX groups and accounts, but if users want to rely on this role to do that, why not. The `dependent` variables were not missing, they were intentionally left out to signify that this role is not designed for dependent operation. Oh well. :-)

Just flatten the `system_users__dependent_groups` variable and I'll merge it.

2019-10-21 08:59 UTC, reixd commented
>  The `dependent` variables were not missing, they were intentionally left out to signify that this role is not designed for dependent operation. 

I thought of keeping the role consistent, because other roles also provide "dependent services".

> Just flatten the `system_users__dependent_groups` variable and I'll merge it.

Done

2019-10-22 10:31 UTC, drybjed approved these changes

2019-10-22 10:32 UTC, merged