[debops.roundcube] Update Roundcube to version 1.4.0.
debops/debops pull request #1144
Opened 2019-11-12 01:23 UTC by reixd

This PR updates the current role to support the new v1.4.0 including the elastic responsible skin.

2019-11-13 00:03 UTC, ganto requested changes
Very nice update and extension. Thanks a lot for your effort. However I feel the breaking changes are not really necessary.

Somehow I missed the release of Roundcube 1.4.0. Looks like I need to give it a try.

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> + | from defaults.inc.php to this file to override the defaults.          |
I don't think that's a good idea to re-add these comments here. They don't really make sense, as this is not a sample configuration nor should the user be adviced to copy anything manually into this file.

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> +$config['log_driver'] = 'syslog';
Would be nice to have this as a role variable, no?

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> +//       or (Windows): 'sqlite:///C:/full/path/to/sqlite.db' #}
No need to add windows example. Confusing...

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/defaults/main.yml
> +# This variable is also called `default_server` by Roundcube  .
It's called `default_host` in the Roundcube config, no?

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/defaults/main.yml
> +roundcube__imap_server: 'localhost'
Why you rename the variable? I don't really like this breaking change for no obvious benefit.

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/tasks/main.yml
> +- include: configure_skins.yml
Change to `include_tasks`

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/tasks/configure_skins.yml
> +        and roundcube__git_checkout is defined
I think it's easier to read the code if you move the `when` condition to the `include` and remove the block here. The playbook output is also less noisy if the condition is false.

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/defaults/main.yml
> +roundcube__skin_logo: 'null'
What does `null` mean?

2019-11-13 00:03 UTC, ganto commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> +// Logo image replacement. Specifies location of the image as:
No need to add all these comments. They are redundant with the documentation in the variable defaults. 

I can't see why I originally added them to the template, but they should at least be excluded with `{# ...  #}` to avoid that they end up in the generated config file.

2019-11-13 08:44 UTC, reixd commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> + | from defaults.inc.php to this file to override the defaults.          |
My purpose was to have a template very similar to the oficial `config.inc.php`. Including comments.
Which actually help while developing the template...

What does says the benevolent dictator @drybjed ?

2019-11-13 08:44 UTC, reixd commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> +$config['log_driver'] = 'syslog';
True, wilco

2019-11-13 08:49 UTC, reixd commented on ansible/roles/debops.roundcube/defaults/main.yml
> +# This variable is also called `default_server` by Roundcube  .
Yes it is. But it is kinda confusing. 
I am trying to make it easier to configure...

Any more opinions?

2019-11-13 08:50 UTC, reixd commented on ansible/roles/debops.roundcube/defaults/main.yml
> +roundcube__imap_server: 'localhost'
See https://github.com/debops/debops/pull/1144#discussion_r345631451

2019-11-13 08:52 UTC, reixd commented on ansible/roles/debops.roundcube/tasks/main.yml
> +- include: configure_skins.yml
Good catch!
(https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_includes.html)

2019-11-13 08:53 UTC, reixd commented on ansible/roles/debops.roundcube/tasks/configure_skins.yml
> +        and roundcube__git_checkout is defined
My intention was to have a skin task file, so all special skins configurations in the future land here.

2019-11-13 08:53 UTC, reixd commented on ansible/roles/debops.roundcube/tasks/configure_skins.yml
> +        and roundcube__git_checkout is defined
Any other opinions?

2019-11-13 08:54 UTC, reixd commented on ansible/roles/debops.roundcube/defaults/main.yml
> +roundcube__skin_logo: 'null'
See https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L424

2019-11-13 09:15 UTC, reixd commented
Travis says: [NO](https://travis-ci.org/debops/debops/jobs/611271205?utm_medium=notification&utm_source=github_status)
locally I get all green

2019-11-13 09:16 UTC, drybjed commented on ansible/roles/debops.roundcube/templates/srv/www/sites/config.inc.php.j2
> + | from defaults.inc.php to this file to override the defaults.          |
I think that if these comments were already gone  from the template included in the role, adding them back doesn't have any useful porpose, so this should go.

2019-11-25 17:46 UTC, cultcom commented
Why do you prefer installing nodejs on a webserver in favor of using the official tarball ?

2019-11-26 18:48 UTC, reixd commented
> Why do you prefer installing nodejs on a webserver in favor of using the official tarball ?

Can you please be more specific with your question?

`debops.roundcube` installs roundcube from the official git repo, thus the necessity to compile the (new) CSS files.

2019-11-27 09:55 UTC, cultcom commented
> `debops.roundcube` installs roundcube from the official git repo, thus the necessity to compile the (new) CSS files.

yes, I am questioning this strategy. I think the complexity decreases when the role simply downloads the official tarball and drops dependencies to nodejs and git etc.

I just wanted to hear other opinions about that.

2019-11-27 10:37 UTC, drybjed commented
My view on that is that I want to be protected from third-party projects like Roundcube suddenly vanishing and me being unable to recreate the installation due to the lack of sources. If we have source code cloned somewhere, we can always in such case publish it in a reachable `git` repository so that role can grab that cloned version and install Roundcube again. This is the same strategy as Debian's to include all source code in the repositories, without binary-only packages or vendored code. Any code compilation on the production server, if it's needed, cannot be avoided. An alternative would be to install the application from upstream APT repository, and when that's not available, the user would have to make their own `.deb` package and put it in a local APT repository.

I'm fine with having binary-only installation from upstream (that would be the functional result in this case), as long as installation "from source" is still available as an option. Then this can be selected conditionally by the user via Ansible inventory and both sides should be satisfied.

Don't forget about ahtneticating the source code or binary installs using GPG keys.

2019-12-11 08:21 UTC, merged