[icinga] add variables for defining config files on the master node
debops/debops pull request #1467
Opened 2020-08-14 17:23 UTC by lewer

This is a (simpler) try for achieving this: https://github.com/debops/debops/pull/1418

2020-08-14 20:58 UTC, drybjed requested changes
Nice work. Does that solve your use case, @lewer?

You could also add a task to allow removal of remote configuration files. There's probably nothing in the `zones.d/` by default that would warrant support for configuration diverts/reverts, I imagine.

Is the configuration syntax the same as the `icinga__configuration` variables? You can add a note on that in the variable description.

2020-08-15 12:33 UTC, lewer commented
Thanks @drybjed for your advices, I've modified the code.

Yes, this solves my use case.

One thing I'm not sure: `icinga__master_nodes.0.target` is the DNS record of the master node, and it might be resolvable from the host but not from the controller, wich would make the delegation fail. To address this, an other variable `icinga__master_node_inventory_hostname` would probably be required... I'm not concerned by this, but do you think someone could?

2020-08-16 10:05 UTC, drybjed commented
@lewer Good point with the separate variable for the master node, you should add it and set the first node as the default. Ansible usually handles the delegation via DNS records well enough, but in rare cases that it's incorrect having a variable to define will be useful.

2020-08-16 10:06 UTC, drybjed commented on ansible/roles/icinga/defaults/main.yml
> +
Remove this empty line, otherwise it will show up in the folded view in `vim`.

2020-08-27 06:33 UTC, drybjed approved these changes
Nice work, thanks. :-)

2020-08-27 06:39 UTC, merged