[etc_keeper] Install etckeeper from backports
debops/debops pull request #1566
Opened 2020-11-22 19:55 UTC by imrejonk

Closes #1560

2020-11-22 20:03 UTC, ypid requested changes
LGTM. I only ask for some style changes:

* Consistent form of "etckeeper". It seems the authors want it to be always written as lowercase. Ref: https://etckeeper.branchable.com/README/
* Consistent commit message. Use `[etckeeper]` instead of `[etc_keeper]`.

2020-11-22 20:03 UTC, ypid commented on CHANGELOG.rst
> +  that have a Python 2 environment. Etckeeper is also installed from
```suggestion
  that have a Python 2 environment. etckeeper is also installed from
```

2020-11-22 20:06 UTC, ypid commented
And not to forget `docs/ansible/roles/etckeeper/getting-started.rst`.

2020-11-22 20:10 UTC, imrejonk commented on CHANGELOG.rst
> +  that have a Python 2 environment. Etckeeper is also installed from
Crap, I keep writing etc_keeper... Thanks for spotting this.

2020-11-22 21:12 UTC, imrejonk commented
Docs are updated as well now

2020-11-22 21:14 UTC, ypid approved these changes
LGTM. Thank you. So the Python 3 only future is near :)

2020-12-02 18:44 UTC, drybjed approved these changes
Sounds good. I'll fix the Changelog conflict and add the `etckeeper` `apt_preferences` entry in the common playbook.

2020-12-02 18:57 UTC, merged