Fix netbox-rq service restart and maintenance
debops/debops pull request #1598
Opened 2021-01-17 14:40 UTC by ypid

2021-01-19 12:08 UTC, drybjed requested changes
Thanks. There are some changes I'm not sure about, see the comments below.

2021-01-19 12:08 UTC, drybjed commented on README.md
> +You can find full text of the license in the [GPL-3.0-or-later.txt] file.
Could this identifier be called `LICENSES/GPL-3.0-or-later.txt` so that users can find the correct path visually? I'm not sure if `/` can be used in references in Markdown...

2021-01-19 12:08 UTC, drybjed commented on README.md
> +-->
This file is used to generate the readme for the Python package via `pandoc`, and the contents will show up on Ansible Galaxy and PyPI. I'm not sure if they will correctly interpret the HTML comment in a Markdown file. I'm fine with keeping this detail in `.reuse/dep5` file.

2021-01-19 12:08 UTC, drybjed commented on ansible/roles/global_handlers/handlers/netbox.yml
>           ansible_local.gunicorn.installed|bool)
This might break if `gunucorn` fact is not present. You could wrap this in `|d()` to avoid that:
```
(ansible_local.gunicorn.installed|d())|bool
```

2021-01-19 12:08 UTC, drybjed commented on ansible/roles/global_handlers/handlers/netbox.yml
>    when: (not netbox__app_internal_appserver|bool and
Moving NetBox handlers to global handlers might not be a good idea, since they refer to the default variables in the `netbox` role. Did you check that when you run other DebOps playbooks that don't have `netbox` role included, they don't blow up and Ansible doesn't complain about an undefined variables? I specifically did not move these handlers due to them referring to an internal role variables.

2021-01-19 12:08 UTC, drybjed commented on .gitignore
> +# SPDX-License-Identifier: CC0-1.0
Yeah, I suppose `.gitignore` cannot be copyrighted as such, the same probably goes for `.dockerignore`.

2021-01-19 19:08 UTC, ypid commented on README.md
> +You can find full text of the license in the [GPL-3.0-or-later.txt] file.
As you wish, sounds good to me and it is covered by the spec:

https://spec.commonmark.org/dingus/?text=%5Bfoo%5D%3A%20%2Furl%20%22title%22%0A%0A%5Bfoo%5D%0A

https://spec.commonmark.org/0.29/#link-reference-definitions

2021-01-19 19:09 UTC, ypid commented on README.md
> +-->
https://git.fsfe.org/reuse/tool is the role model right? :) https://git.fsfe.org/reuse/tool/raw/branch/master/README.md

I have used HTML comments in Markdown for some time and have not noticed issues.

Also, I agree with REUSE that when possible, the info should be in the file itself.

2021-01-19 19:10 UTC, ypid commented on ansible/roles/global_handlers/handlers/netbox.yml
>           ansible_local.gunicorn.installed|bool)
Good catch :+1:
But the extra parenthesis are probably not needed.

2021-01-19 19:11 UTC, ypid commented on ansible/roles/global_handlers/handlers/netbox.yml
>    when: (not netbox__app_internal_appserver|bool and
I just tried it (after fixing the missing import of the handlers), another role using global handlers did not blow up. But now I know the reason why you left the NetBox role out so I undid this.

2021-01-19 19:14 UTC, ypid commented
Good review :+1: I should have addressed all of your feedback.

2021-01-20 14:37 UTC, drybjed commented on README.md
> +-->
Alright then, let's see what breaks. :)

2021-01-20 14:38 UTC, drybjed approved these changes

2021-01-20 14:39 UTC, merged