[owncloud] add variable for release channel
debops/debops pull request #1609
Opened 2021-01-23 15:34 UTC by bleuchtang

Since Nexcloud 17 we should change the default channel to stable ([default channel for CE](https://nextcloud.com/release-channels/)) . This PR add a variable to set the channel outside the role and define this variable to stable for nexcloud > 17.0.

2021-01-23 15:56 UTC, ypid requested changes
Good catch! I confirm that `production` is a legacy setting. I tested it in the GUI and as soon as I select another value, `production` disappears. It still worked so I guess they have stable as fallback.

2021-01-23 15:56 UTC, ypid commented on ansible/roles/owncloud/defaults/main.yml
> +                            else "production" }}'
Indention should match. See the other if conditions in that file.

Also "Release channel" as variable description does not add much value to the variable name. Can you add more context? Reference to the URL would be fine. I try to limit the redundancy we have to maintain here.

2021-01-23 19:32 UTC, ypid commented on ansible/roles/owncloud/defaults/main.yml
> +# * Nextcloud ``18.0``
Something is wrong with this commit.

2021-01-27 08:37 UTC, bleuchtang commented on ansible/roles/owncloud/defaults/main.yml
> +# * Nextcloud ``18.0``
Grrr, sorry.

2021-01-27 20:16 UTC, ypid approved these changes
LGTM, thanks!

2021-01-28 09:18 UTC, drybjed approved these changes
Nicely done, thanks. I'll backport it as well.

2021-01-28 09:21 UTC, merged