roundcube: Lock contextmenu-plugin version for roundcube 1.4.x
debops/debops pull request #1891
Opened 2021-10-24 08:55 UTC by tumd

Since the release of Roundcube 1.5 a couple of days ago, the plugin [johndoh/contextmenu](https://github.com/johndoh/roundcube-contextmenu/releases) also released a new version that doesn't seem to be compatible with Roundcube 1.4.x.

This commit should lock the johndoh/contextmenu version to 3.2.1 when Roundcube 1.4.x is installed.
I have only tested this change with Roundcube 1.4.11.

Closes: #2000

2021-11-02 14:57 UTC, imrejonk requested changes
Thanks for the PR! A few suggestions:
- `version_compare` was [renamed](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#comparing-versions) to `version` in Ansible 2.5.
- I think it makes more sense to compare the version against `roundcube__git_version`. This variable always contains the version number that is being deployed, while the version found in the local facts is only updated after the plugin installation task.

2022-02-13 09:17 UTC, tumd commented
The PR has been updated, but it is untested by me, as I currently run roundcube 1.5.

2022-03-02 23:52 UTC, prahal commented
I tested the commit above current upstream 8af5329925af73a3d343213fdcdf1601ef9441f7.
Works. I am with current roundcube version, that is 1.4.13.

2022-03-31 04:21 UTC, imrejonk approved these changes
Hey! Sorry for the wait, I didn't notice that you pushed changes. This looks good! I took the liberty to add a changelog entry to your PR, hope you don't mind :)

2022-07-24 10:13 UTC, drybjed approved these changes
Looks good, thanks. Sorry for a late merge. I'll backport this to the stable releases as well.

2022-07-24 10:16 UTC, merged