Install "gunicorn3" package for Py3 web applications.
debops/debops pull request #506
Opened 2018-10-29 14:45 UTC by cultcom

Add the "gunicorn3" packages to the base_packages.

2018-10-29 19:26 UTC, drybjed commented
@cultcom. Sounds good, however what would you say about converting this role to use `debops.python` to install the Py2 and Py3 packages, ie. `gunicorn` and `python-setproctitle` for Py2, `gunicorn3` and `python3-setproctitle` for Py3. You could look at the `debops.redis_server` role/playbook for example usage, and the `debops.python` documentation.

I can look at this in a week or so (currently on holidays) if you are not sure how to make the conversion.

2018-10-30 13:38 UTC, cultcom commented
happy holiday than.

There is still another issue with the generated config file for gunicorn. With gunicorn3 it complains about malformed JSON data.

2018-10-30 14:57 UTC, cultcom commented
Ok, have a look at my last changes then. I hope I understood you correctly. In case I actually did I would suggest to remove the base_packages handling from this role completely as well.

I also added a fix for some JSON errors leading to decoder exceptions.

2018-10-31 07:40 UTC, drybjed commented
@cultcom Nicely done! I agree that `gunicorn__base_packages` variable can be dropped; remove it and I think this PR will be ready for merging.

As for the gunicorn config file, it will have to be ignored by pyCodeStyle and the Jinja wrapping can then be dropped completely, this should solve several issues during servie execution. It can be done in a separate step.

2018-10-31 12:26 UTC, cultcom commented
@drybjed I removed the package installation tasks as requested but I don not completely understand your point regarding the config file. With my last changes the service starts running at least.

Another point might be the systemd service files. They currently call "gunicorn" which is no problem when you prepend a Py3 virtualenv path. But without venv a Py3 app should be called with "gunicorn3" instead...

2018-11-05 12:58 UTC, drybjed commented
@cultcom Perhaps this could be solved by adding `item.gunicorn_binary` parameter that would specify `/usr/bin/gunicorn` by default and could be overriden on a per-app basis. Do you want to add that as well before I merge this PR? If to, don't forget to update the documentation.

2018-11-05 15:57 UTC, cultcom commented
I added a item.binary option which configures the service per app and a global gunicorn__binary as a default fallback.

2018-11-06 07:56 UTC, drybjed requested changes
Nicely done, although there a few minor changes I'd like to see.

The `debops.gunicorn` role is used in the `ansible/playbooks/service/netbox.yml` playbook. Because you changed the dependencies of `debops.gunicorn`, you should also update all of the other playbooks it is included in - the soft dependencies will not be pulled in automatically. I think that this also warrants a mention in the Changelog "Changed" section, in case that other `debops.gunicorn` users will have to do the same in their own playbooks.

You should also add the explanation of the `binary` parameter to the documentation section that describes the `gunicorn__applications` configuration. Putting it in the example without short explanation of its use might be confusing.

Something to think for the future: the `debops.python` role provides facts that indicate if support for Python 2 is enabled or not. This could be used to automatically enable/disable `gunicorn3` default binary. DebOps is not fully Py3-only compatible yet, so this can be implemented later.

2018-11-06 07:56 UTC, drybjed commented on ansible/roles/debops.gunicorn/templates/etc/systemd/system/gunicorn@application.service.d/instance.conf.j2
> +ExecStart={{ (item.python + ' ') if item.python|d() else '' }}/usr/bin/{{ item.binary if (item.binary is defined) else gunicorn__binary }} --config=/etc/gunicorn/%i.conf.py ${GUNICORN_OPTS} {{ item.a
I think that this can be shortened with:
```
{{ item.binary | d(gunicorn__binary) }}
```

2018-11-06 07:56 UTC, drybjed commented on ansible/roles/debops.gunicorn/templates/etc/systemd/system/gunicorn@.service.j2
> +ExecStart=/usr/bin/{{ item.binary if (item.binary is defined) else gunicorn__binary }} --config=/etc/gunicorn/%i.conf.py ${GUNICORN_OPTS}
This change doesn't make sense - per-item variables are available in the override file, not in the main service file. You should only specify `gunicorn__binary` here.

2018-11-06 10:21 UTC, drybjed approved these changes
Nicely done, thanks!

2018-11-06 11:34 UTC, merged