[debops.cryptsetup] Fixes present state flag behavior
debops/debops pull request #725
Opened 2019-03-20 12:56 UTC by jpeeters

The state flag of the plaintext block devices controls if the block
devices must be opened or not and if the filesystem on it must be
mounted.

In case the filesystem is not managed by the role and the state flag is
set to `present', the plaintext block device should not be closed as it may be
used by other roles like debops.lvm.

Then, this commit adds an additional condition inside the teardown procedure
at the end of the role in order to implemente this use case.

In a further patch, the lvm-based use case should be better covered with
explicit configuration other than simply disable filesystem management.

2019-03-20 13:43 UTC, drybjed submitted a review, later dismissed
Sounds reasonable to me. I'll wait for @ypid a day or two before merging, in case he sees any issues.

2019-03-21 22:07 UTC, ypid commented
Sounds also reasonable to me, thanks @jpeeters. I would like to check and test this in more detail. @drybjed Please wait with merging until Tuesday. Until then I should be able review it more.

2019-03-25 21:36 UTC, ypid requested changes
This change is not in line with the docs of the role. Refer to https://docs.debops.org/en/master/ansible/roles/debops.cryptsetup/defaults-detailed.html#cryptsetup-devices-state-present So this would be a breaking change. I would suggest to introduce a new state called "mapped" instead which does what you want. Please update the docs as well ;-)

2019-03-28 08:12 UTC, jpeeters commented
Ok I got i @ypid. Thx for the review. I will deal with this next week.

2019-06-01 14:26 UTC, jpeeters commented
@ypid @drybjed I pushed a new commit that should implement proposed suggestions from @ypid. Let me know if this requires more improvements. This docs should be up to date too.

2019-06-10 19:29 UTC, ypid commented
@jpeeters Thanks for the update. I would like to review and this this a bit. Will probably take a few weeks.

2019-06-15 22:20 UTC, ypid requested changes
Thanks for the update. I have an issue with this patch because it does not "compile" so I assume it is not so well tested. After I fixed the "compile error", the "Manage fstab and mount state of the plaintext device mapper targets" task fails. This task also needs to be excluded from the "mapped" state. I stopped my review of the tasks file at this point.

Regarding the docs, I know they are quite extensive and not easy to change. It would be great if you could read defaults-detailed.rst as a whole and see if any other options of the role might be affected by the new state. At a minimum the difference between manage_filesystem and the mapped state should be mentioned. Bonus points for a full example showing an actual use case for the `mapped` state. This role is quite complex and I feel it needs easy and practical examples for it to be usable.

2019-06-15 22:20 UTC, ypid commented on ansible/roles/debops.cryptsetup/tasks/manage_devices.yml
> +         not (item.state|d(cryptsetup__state) in ['mapped'])
Missing `)`.

2022-06-19 19:20 UTC, closed without merging