[debops.dovecot] Add local facts
debops/debops pull request #866
Opened 2019-07-05 14:16 UTC by amette

Without these Postfix doesn't configure SASL auth.

2019-07-06 09:42 UTC, drybjed requested changes
Thanks! Looks like there are issues with the fact script, check the Travis-CI status for details. You could try running the `make test` command in the DebOps monorepo root directory to run the Travis-CI tests locally, after installing needed packages.

2019-07-06 09:42 UTC, drybjed commented on ansible/roles/debops.dovecot/tasks/main.yml
> +    group: 'root'
You should remove the `owner` and `group` keywords from the tasks, since the role will be executed as `root` anyway.

2019-07-06 09:42 UTC, drybjed commented on ansible/roles/debops.dovecot/templates/etc/ansible/facts.d/dovecot.fact.j2
> +output = {'installed': True}
This fact could be more dynamic by checking the existence of the `dovecot` command during execution. Check the fact of the `debops.ansible` role for a good example.

2019-07-10 16:04 UTC, amette commented
Cool! Thanks for the feedback. I'll look into it in the next days.

2020-02-11 20:25 UTC, drybjed commented
The Ansible local facts have been added to the `dovecot` role in a different PR, closing this one since it is now redundant.

2020-02-11 20:25 UTC, closed without merging